baseURL = "https://www.linkace.org/"
languageCode = "en-us"
title = "LinkAce - Your self-hosted bookmark archive. Free and open source."
assetDir = "./assets/dist"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  DocsRepo = "https://github.com/Kovah/LinkAce-Website/"
  DemoUrl = "https://demo.linkace.org"
  WikiDockerSetupUrl = "/docs/v2/setup/setup-with-docker/"
  WikiServerSetupUrl = "/docs/v2/setup/setup-without-docker/"
  DockerHub = "https://hub.docker.com/r/linkace/linkace/"
  Github = "https://github.com/Kovah/LinkAce/"
  Twitter = "https://twitter.com/linkaceapp"
  Mastodon = "https://mastodon.social/@linkace"
  Community = "https://github.com/Kovah/LinkAce/discussions/"
  Zapier = "https://zapier.com/apps/linkace/integrations"
  AboutMeMastodon = "https://mastodon.social/@Kovah"
  AboutMeWebsite = "https://kovah.de"
  AboutMeTwitter = "https://twitter.com/kevinwoblick"

# [outputs]
#   page = ['HTML', 'Algolia']

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
